### ISSUE TITLE
Documention in this md file Test-EsxiCertMgmtChecks.md needs correction

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#116]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Module Version

1.5.3

### Suggestion

The description in Test-EsxiCertMgmtChecks.md is given for a wrong cmdlet (Test-VCFCertMgmtChecks ) which should be Test-EsxiCertMgmtChecks

**Comment by tenthirtyam** [comment]
Resolved.
