### ISSUE TITLE
Add pester testcases for automated testing of the code

### ISSUE THREAD

**Issue by Ashwini-Ravi** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#117]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Today we have manual testing process to test the VMware.CloudFoundation.CertificateManagement code, but this has to be put in CD/CI pipeline to automate the testing process for repeatable testing before pushing to public GitHub to test on the quality of the fix and to minimize regression defects. This also ensures, time consumed for less in testing the code.

### Use Case(s)

Suppose if manual testing takes about x time, automation of the same takes x/2. Also it is more reliable and you can test even negative testcases easily.

### Potential Configuration

writing pester testcases to automate the testing process
In the current code structure, there will be /tests folder, under that pester testcases will be available for testing
Also it requires input json file to hold all the credential information

**Comment by tenthirtyam** [comment]
Reassigning to @sowjuec.
