### ISSUE TITLE
Enhance `Get-vSANHealthSummary` similar `VMware.CloudFoundation.PowerManagement`

### ISSUE THREAD

**Issue by bhumitra** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#31]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Enhance `Get-vSANHealthSummary` similar `VMware.CloudFoundation.PowerManagement`.

### Use Case(s)

NA

### Potential Configuration

NA

**Comment by bhumitra** [comment]
I have enhanced the cmdlet, but it cannot be made similar to Test-VSANHealth in Power Management module. The requirements here are different, and even though both functions use same cmdlets internally, the way the way they report status is different. e.g. Test-VSANHealth considers warnings as a PASSED/HEALTHY state. 

https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-power-management/issues

**Comment by bhumitra** [comment]
I think we should close this issue and address the enhancements of reporting warnings in the power-management module.

**Comment by tenthirtyam** [comment]
closing.
