### ISSUE TITLE
Add support for ESXi certificate replacement without performing full evacuation when entering maintenance mode

### ISSUE THREAD

**Issue by bhumitra** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#32]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently, when using vSAN, it is required to perform full evacuation of VMs when putting the ESXi host in maintenance mode. 

Add support for ESXi certificate replacement without performing full evacuation when entering maintenance mode.

### Use Case(s)

NA

### Potential Configuration

NA

**Comment by tenthirtyam** [comment]
Pulled forward to the v1.6.0 milestone and assigned to Kevin Teng.

It looks like this would just be a change to `Install-EsxiCertificate` to support the option to pass the `VsanDataMigrationMode` parameter if the `primaryDatastoreType` is `vsan`.

Pass the value to `Set-EsxiConnectionState` which already supports the three methods: One of `Full`, `EnsureAccessibility`, or `NoDataMigration`.

If `EnsureAccessibility`, output a confirm warning for that you should ensure they have sufficient backups. Must be capable of being skipped if `-Confirm:` is used.

Add the `VsanDataMigrationMode` parameter to `Install-EsxiCertificate` it as a parameter, but it only be applicable for vSAN. If not explicitly provided default to `Full`.

Additionally, adding the option to migrate powered off VMs by adding a `migratePoweredOffVms` as a `bool` and default to `false` will be considered.

Update all documentation (cmdlet examples and references) based on the changes.
