### ISSUE TITLE
Enhance `Restart-ESXiHost` to support quick boot

### ISSUE THREAD

**Issue by bhumitra** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#34]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Verify if this feature is supported. If yes, then enhance the cmdlet 

### Use Case(s)

NA

### Potential Configuration

NA

**Comment by bhumitra** [comment]
This feature is not supported by the existing powershell cmdlets. Closing this.

**Comment by tenthirtyam** [comment]
**Reference**: Feature Ask for [ESXi Quickboot via API/H5/PowerCLI](https://powercli.ideas.aha.io/ideas/PCLI-I-238)
