### ISSUE TITLE
Review opportunities to simplify cmdlets

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#61]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

As of v1.3.0, the module now extends support to SDDC Manager certificate operations.

As we move forward, we have an opportunity to review and uncover where we have options to simplify.

For example, we have:

- `Get-EsxiCertificateThumbprint` and `Get-vCenterCertificateThumbprint`
- `Request-EsxiCsr` and `Request-SddcCsr`
- `Install-EsxiCertificate` and `Install-SddcCertificate`

What if we could provide a single cmdlet for each of those bullets to perform the action based on the target?

For example:

```powershell
PS > Get-VcfCertificateThumbprint -esxi ...
PS > Get-VcfCertificateThumbprint -vc ...

PS > Request-VcfCsr -esxi ...
PS > Request-VcfCsr -sddcManager ...

PS > Install-VcfCertificate -esxi ...
PS > Install-VcfCertificate -sddcManager ...

PS > Set-VcfCertificateAuthority -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -certAuthority microsoft -certAuthorityFqdn rpl-ad01.rainpole.io -certAuthorityUser svc-vcf-ca -certAuthorityPass VMw@re1! -certAuthorityTemplate VMware
PS > Set-VcfCertificateAuthority -server sfo-vcf01.sfo.rainpole.io -user administrator@vsphere.local -pass VMw@re1! -certAuthorityFqdn rpl-ad01.rainpole.io -certAuthority openssl 
```

It could either be done with a wrapper or by updated cmdlets.

### Use Case(s)

Simplify the use of cmdlets for certificate operations.

### Potential Configuration

To be determined.

**Comment by bhumitra** [comment]
I will leave Set-SddcCertificateAuthority as is instead of renaming it to - Set-VcfCertificateAuthority as the CA is set in SDDC Mgr. .
