### ISSUE TITLE
`Install-VCFCertificate` not working on Photon OS 5 

### ISSUE THREAD

**Issue by m-gustafsson** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#92]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/blob/main/CODE_OF_CONDUCT.md).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### PowerShell Version

7.3.4

### PowerCLI Version

13.2

### Module Version

1.4.1

### PowerValidatedSolutions Version

2.7.1

### PowerVCF Version

2.4.0

### Guest Operating System

Photon OS 5

### Environment Details

Standard VMware internal MaaS deployment. Photon OS 5 OVA from: https://packages.vmware.com/photon/5.0/GA/ova/photon-hw15-5.0-dde71ec57.x86_64.ova

Environmental variables set as
`$sddcManagerFqdn = "sddc-manager.vrack.vsphere.local"`
`$sddcManagerUser = "administrator@vsphere.local"`
`$sddcManagerPass = "VMware123!"`
`$workloadDomain = "sddcId-1001"`
`$cluster = "SDDC-Cluster1"`
`$certificateDirectory = "/root/CRT"`
`$certificateFileExt = ".crt"`

### Description

Followed https://docs.vmware.com/en/VMware-Cloud-Foundation/5.0/vcf-operations/GUID-F431F343-B55C-495A-BE92-32483AC825D7.html#GUID-748DCB72-8610-44CA-B288-4FF598C9427D__GUID-BBB73B3E-1391-4A5E-A5B6-D79CD600BCB3 for replacing ESXi certificates in the management domain. All commands up until `Install-VCFCertificate` run without issues. 

`Install-VCFCertificate -esxi -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $workloadDomain -cluster $cluster -certificateDirectory $certificateDirectory  -certificateFileExt $certificateFileExt` runs, for 15 seconds, then but all 4 hosts in the management cluster are skipped. No certificates are uploaded and no error is displayed.

### Error or Debug Output

No error output. 

### Expected Behavior

Hosts to enter maintenance mode with full data evacuation, certificate replaced and host rebooted in a rolling fashion. 

### Actual Behavior

No certificates are replaced on the hosts. 

### Steps to Reproduce

Install Photon OS 5

`tdnf -y update`
`tdnf -y install wget tar git patch build-essential gcc zlib-devel openssl-devel powershell`

Set variables and run `Install-VCFCertificate`

### Screenshots

![image (24)](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/assets/53911488/c888552a-10ad-44eb-a67c-e3c46087e955)

**Comment by tenthirtyam** [comment]
Assigning to Kevin Teng (@garlicNova) for triage.
