### ISSUE TITLE
`Install-VCFCertificate` not working on macOS

### ISSUE THREAD

**Issue by m-gustafsson** [vmware/powershell-module-for-vmware-cloud-foundation-certificate-management#93]
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/blob/main/CODE_OF_CONDUCT.md).
- [x] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [x] Do not leave "+1" or other comments that do not add relevant information or questions.
- [x] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### VMware Cloud Foundation

5.1

### PowerShell Version

7.3.4

### PowerCLI Version

13.1

### Module Version

1.4.0

### PowerValidatedSolutions Version

2.6.0

### PowerVCF Version

2.4.0

### Guest Operating System

macOS 13.6 build 22G120

### Environment Details

Standard VMware internal MaaS deployment.

Environmental variables set as:

```powershell
$sddcManagerFqdn = "sddc-manager.vrack.vsphere.local"
$sddcManagerUser = "administrator@vsphere.local"
$sddcManagerPass = "VMware123!"
$workloadDomain = "sddcId-1001"
$cluster = "SDDC-Cluster1"
$certificateDirectory = "/Users/mgustafsson/CRT"
$certificateFileExt = ".crt"
```

### Description

Followed https://docs.vmware.com/en/VMware-Cloud-Foundation/5.0/vcf-operations/GUID-F431F343-B55C-495A-BE92-32483AC825D7.html#GUID-748DCB72-8610-44CA-B288-4FF598C9427D__GUID-BBB73B3E-1391-4A5E-A5B6-D79CD600BCB3 for replacing ESXi certificates in the management domain. All commands up until `Install-VCFCertificate` run without issues. 

`Install-VCFCertificate -esxi -server $sddcManagerFqdn -user $sddcManagerUser -pass $sddcManagerPass -domain $workloadDomain -cluster $cluster -certificateDirectory $certificateDirectory  -certificateFileExt $certificateFileExt` runs, for 1min 55 seconds, then but all 4 hosts in the management cluster are skipped. No certificates are uploaded and no error is displayed.

Tried running without variables and only for a single host, no difference. Command runs for 43 seconds then the prompt is skipped. 

### Error or Debug Output

No error output.

### Expected Behavior

Hosts to enter maintenance mode with full data evacuation, certificate replaced and host rebooted in a rolling fashion. 

### Actual Behavior

No certificates are replaced on the hosts. 

### Steps to Reproduce

Install Powershell on macOS, install the modules, set the variables and run the `Install-VCFCertificate` commandlet. 

### Screenshots

![image (25)](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/assets/53911488/8b0f2889-59b4-4387-89f3-0368884c3ea2)

**Comment by tenthirtyam** [comment]
The same issue is seen on Linux, correct?

**Comment by tenthirtyam** [comment]
Assigning to Kevin Teng (@garlicNova) for triage.

**Comment by m-gustafsson** [comment]
> The same issue is seen on Linux, correct?

Correct, but I raised a separate issue for that. https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-certificate-management/issues/92
